version: "3.3"
services:
  web:
    build: .
    ports:
      - "80:80"
  db:
    image: "postgres:latest"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      #- "./.mysql-data/db:/var/lib/mysql"
    ports:
      - "5432:5432"
    environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgress
          - POSTGRES_DB=patika